# ???????? JDBC-???????, ??????? p6spy ???????????
driverlist=com.mysql.cj.jdbc.Driver

# ?????? ??????: ?????????? ???????? SQL ? ?????????????? ???????????
logMessageFormat=com.p6spy.engine.spy.appender.MultiLineFormat

# ???????? SQL ? ??????????? ????? (??????? IDEA)
appender=com.p6spy.engine.spy.appender.StdoutLogger